name: Run test with rime-docker
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bluejamkmy/rime-docker:latest
    steps:
      - uses: actions/checkout@v1
      - run: ls -a
      - run: rime test
