name: Run test with rime-docker
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bluejamkmy/rime-docker:latest
      volumes:
        - .:/rime_project
    steps:
      - uses: actions/checkout@v1
      - run: |
          pwd
          ls -a
