name: Run test with rime-docker
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bluejamkmy/rime-docker:latest
    steps:
      - uses: actions/checkout@v1
      - run: rime test
  deploy-summary:
    runs-on: ubuntu-latest
    container:
      image: bluejamkmy/rime-docker:latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v1
      - name: Generate a summary HTML
        run: |
          rime htmlify_full -k
          sed "s/http:\/\//https:\/\//" summary.html
          mkdir summary
          mv summary.html summary/index.html
      - name: Deploy github pages
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./summary
